/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FlashcardsSetsImport } from './routes/flashcards-sets'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const FlashcardsSetsRoute = FlashcardsSetsImport.update({
  id: '/flashcards-sets',
  path: '/flashcards-sets',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/flashcards-sets': {
      id: '/flashcards-sets'
      path: '/flashcards-sets'
      fullPath: '/flashcards-sets'
      preLoaderRoute: typeof FlashcardsSetsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/flashcards-sets': typeof FlashcardsSetsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/flashcards-sets': typeof FlashcardsSetsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/flashcards-sets': typeof FlashcardsSetsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/flashcards-sets'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/flashcards-sets'
  id: '__root__' | '/' | '/flashcards-sets'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlashcardsSetsRoute: typeof FlashcardsSetsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlashcardsSetsRoute: FlashcardsSetsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/flashcards-sets"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/flashcards-sets": {
      "filePath": "flashcards-sets.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
