/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as FlashcardsSetsIndexImport } from './routes/flashcards-sets.index'
import { Route as FlashcardsSetsCreateImport } from './routes/flashcards-sets.create'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FlashcardsSetsIndexRoute = FlashcardsSetsIndexImport.update({
  id: '/flashcards-sets/',
  path: '/flashcards-sets/',
  getParentRoute: () => rootRoute,
} as any)

const FlashcardsSetsCreateRoute = FlashcardsSetsCreateImport.update({
  id: '/flashcards-sets/create',
  path: '/flashcards-sets/create',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/flashcards-sets/create': {
      id: '/flashcards-sets/create'
      path: '/flashcards-sets/create'
      fullPath: '/flashcards-sets/create'
      preLoaderRoute: typeof FlashcardsSetsCreateImport
      parentRoute: typeof rootRoute
    }
    '/flashcards-sets/': {
      id: '/flashcards-sets/'
      path: '/flashcards-sets'
      fullPath: '/flashcards-sets'
      preLoaderRoute: typeof FlashcardsSetsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/flashcards-sets/create': typeof FlashcardsSetsCreateRoute
  '/flashcards-sets': typeof FlashcardsSetsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/flashcards-sets/create': typeof FlashcardsSetsCreateRoute
  '/flashcards-sets': typeof FlashcardsSetsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/flashcards-sets/create': typeof FlashcardsSetsCreateRoute
  '/flashcards-sets/': typeof FlashcardsSetsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/flashcards-sets/create' | '/flashcards-sets'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/flashcards-sets/create' | '/flashcards-sets'
  id: '__root__' | '/' | '/flashcards-sets/create' | '/flashcards-sets/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlashcardsSetsCreateRoute: typeof FlashcardsSetsCreateRoute
  FlashcardsSetsIndexRoute: typeof FlashcardsSetsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlashcardsSetsCreateRoute: FlashcardsSetsCreateRoute,
  FlashcardsSetsIndexRoute: FlashcardsSetsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/flashcards-sets/create",
        "/flashcards-sets/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/flashcards-sets/create": {
      "filePath": "flashcards-sets.create.tsx"
    },
    "/flashcards-sets/": {
      "filePath": "flashcards-sets.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
